#!/bin/bash
CP="exe:test/lib/hamcrest-core-1.3.jar:test/lib/junit-4.13.2.jar:src/lib/mysql-connector-java-5.1.46.jar"
SP="test:src"
make clean
echo "COMPILE"
javac -d exe -cp $CP --source-path test:src src/Main.java
echo "EXECUTE"
time java -cp $CP Main