openapi: 3.0.3
info:
  version: 1.0.0
  title: Exercise 5.4
  description: "Versió OpenAPI del la solució publicada a <https://atenea.upc.edu/mod/resource/view.php?id=2158292>. Suposem que totes les crides necessiten autentificació via una api_key que indentifica un usuari determinat. Només es poc accedir als missatges de l'usuari autentificat."
servers:
  - url: 'http://localhost:8080/RevPollution/services'

paths:
  /login/login:
    get:
      tags:
      - users
      summary: Iniciar sesión.
      parameters:
      - name: username
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        404:
          description: 'Error: Not Found'
        401:
          description: 'Error: Unauthorized'
        403:
          description: 'Error: Forbidden'
      security:
      - ApiKeyAuth: []
  /concentrations:
    get:
      tags:
      - missatges
      summary: Obtenir Missatges Usuari
      parameters:
      - name: idStation
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/concentration.yml'
        404:
          description: 'Error: Not Found'
        401:
          description: 'Error: Unauthorized'
        403:
          description: 'Error: Forbidden'
      security:
      - ApiKeyAuth: []
  /dailyExpo:
    get:
      tags:
      - exposicion
      summary: Obtener la exposición diaria.
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '/home/erik/Escritorio/UNI/3/Q6/PES/BackEnd/doc/components/schemas/expo.yml'
        404:
          description: 'Error: Not Found'
        401:
          description: 'Error: Unauthorized'
        403:
          description: 'Error: Forbidden'
      security:
      - ApiKeyAuth: []
  /dailyExpo/addExpo:
    post:
      tags:
      - exposicion
      summary: Añadir la exposición en una ubicación.
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: lat
        in: query
        required: true
        schema:
          type: number
      - name: lon
        in: query
        required: true
        schema:
          type: number
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: boolean
        404:
          description: 'Error: Not Found'
        401:
          description: 'Error: Unauthorized'
        403:
          description: 'Error: Forbidden'
      security:
      - ApiKeyAuth: []
  /logros:
    get:
      tags:
      - logros
      summary: Obtener la lista de logros completa.
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '/home/erik/Escritorio/UNI/3/Q6/PES/BackEnd/doc/components/schemas/logro.yml'
        404:
          description: 'Error: Not Found'
        401:
          description: 'Error: Unauthorized'
        403:
          description: 'Error: Forbidden'
      security:
      - ApiKeyAuth: []
  /logros/info:
    get:
      tags:
      - logros
      summary: Obtener información de un logro.
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      - name: tier
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '/home/erik/Escritorio/UNI/3/Q6/PES/BackEnd/doc/components/schemas/logro.yml'
        404:
          description: 'Error: Not Found'
        401:
          description: 'Error: Unauthorized'
        403:
          description: 'Error: Forbidden'
      security:
      - ApiKeyAuth: []
  /signup:
    post:
      tags:
      - users
      summary: Obtener información de un logro.
      parameters:
      - name: username
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      - name: email
        in: query
        required: true
        schema:
          type: string
      - name: telf
        in: query
        required: true
        schema:
          type: string
      - name: name
        in: query
        required: true
        schema:
          type: string
      requestBody:
        description: Foto de perfil
        required: false
        content:
          text/plain:
              schema:
                type: string
      responses:
        200:
          description: successful operation
          content:
            
            application/json:
              schema:
                type: boolean
        404:
          description: 'Error: Not Found'
        401:
          description: 'Error: Unauthorized'
        403:
          description: 'Error: Forbidden'
      security:
      - ApiKeyAuth: []
